### ISSUE TITLE
Toggle link circles

### ISSUE THREAD

**Issue by tigerros** [talal/ilm#12]
The maroon circles next to links are kind of non-standard. It would be good if they could be removed.

**Comment by ironupiwada** [comment]
@talal Just like @tigerros. I would suggest that the link circles should be optional, and these lines:

```
// Show a small maroon circle next to external links.
  show link: it => {
    // Workaround for ctheorems package so that its labels keep the default link styling.
    if type(it.dest) == label { return it }
    it
    h(1.6pt)
    super(box(height: 3.8pt, circle(radius: 1.2pt, stroke: 0.7pt + rgb("#993333"))))
  }
  ```
  
  could be disabled on the user's request (maybe using an option in ilm.with?).

**Comment by talal** [comment]
Fixed in https://github.com/talal/ilm/commit/3687f6bf0a84c63d104f3e80bba2cc9615d7779d .

Kindly wait until https://github.com/typst/packages/pull/855 is merged and then use:

```typst
#import "@preview/ilm:1.2.0": *
```

Alternatively, you can copy over the latest version of [lib.typ](https://github.com/talal/ilm/blob/main/lib.typ) file and use that in your project.
